import {
  UserRow,
  OrderRow,
  FaultBatch,
  ProcessingOrder,
} from "@/components/table/CustomizableTableHeader";

export const userData: UserRow[] = [
  {
    id: "U001",
    username: "alice",
    email: "alice@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2025-09-10 14:32",
    actions: ["d", "r"],
  },
  {
    id: "U002",
    username: "bob",
    email: "bob@example.com",
    role: "Manager",
    status: "Inactive",
    lastLogin: "2025-09-05 09:12",
    actions: ["d"],
  },
  {
    id: "U003",
    username: "carol",
    email: "carol@example.com",
    role: "Staff",
    status: "Suspended",
    lastLogin: "2025-08-30 18:47",
    actions: ["d", "r"],
  },
];

export const orderData: OrderRow[] = [
  {
    orderId: "ER-2025-001",
    date: "01-01-2025",
    warehouse: "Warehouse 1",
    priority: "High",
    handle: "Pending",
    actions: ["edit", "check"],
  },
  {
    orderId: "ER-2025-002",
    date: "02-02-2025",
    warehouse: "Warehouse 1",
    priority: "Low",
    handle: "Completed",
    actions: ["edit", "check"],
  },
  {
    orderId: "ER-2025-003",
    date: "03-03-2025",
    warehouse: "Warehouse 2",
    priority: "High",
    handle: "In progress",
    actions: ["edit", "check"],
  },
  {
    orderId: "ER-2025-004",
    date: "04-04-2025",
    warehouse: "Warehouse 3",
    priority: "Medium",
    handle: "Pending",
    actions: ["edit", "check"],
  },
  {
    orderId: "ER-2025-005",
    date: "01-01-2025",
    warehouse: "Warehouse 1",
    priority: "High",
    handle: "Pending",
    actions: ["edit", "check"],
  },
  {
    orderId: "ER-2025-006",
    date: "01-01-2025",
    warehouse: "Warehouse 1",
    priority: "High",
    handle: "Pending",
    actions: ["edit", "check"],
  },
  {
    orderId: "ER-2025-007",
    date: "01-01-2025",
    warehouse: "Warehouse 1",
    priority: "High",
    handle: "Pending",
    actions: ["edit", "check"],
  },
  {
    orderId: "ER-2025-008",
    date: "01-01-2025",
    warehouse: "Warehouse 1",
    priority: "High",
    handle: "Pending",
    actions: ["edit", "check"],
  },
  {
    orderId: "ER-2025-009",
    date: "01-01-2025",
    warehouse: "Warehouse 1",
    priority: "High",
    handle: "Pending",
    actions: ["edit", "check"],
  },
  {
    orderId: "ER-2025-010",
    date: "01-01-2025",
    warehouse: "Warehouse 1",
    priority: "High",
    handle: "Pending",
    actions: ["edit", "check"],
  },
  {
    orderId: "ER-2025-011",
    date: "01-01-2025",
    warehouse: "Warehouse 1",
    priority: "High",
    handle: "Pending",
    actions: ["edit", "check"],
  },
  {
    orderId: "ER-2025-012",
    date: "01-01-2025",
    warehouse: "Warehouse 1",
    priority: "High",
    handle: "Pending",
    actions: ["edit", "check"],
  },
  {
    orderId: "ER-2025-013",
    date: "01-01-2025",
    warehouse: "Warehouse 1",
    priority: "High",
    handle: "Pending",
    actions: ["edit", "check"],
  },
  {
    orderId: "ER-2025-014",
    date: "01-01-2025",
    warehouse: "Warehouse 1",
    priority: "High",
    handle: "Pending",
    actions: ["edit", "check"],
  },
];

export const faultBatchData: FaultBatch[] = [
  {
    id: "SI-2025-001",
    date: "01-01-2025",
    status: "Pending",
    priority: "High",
    checked: true,
  },
  {
    id: "SI-2025-002",
    date: "02-02-2025",
    status: "Completed",
    priority: "Low",
    checked: true,
  },
  {
    id: "SI-2025-003",
    date: "03-03-2025",
    status: "In progress",
    priority: "High",
    checked: true,
  },
  {
    id: "SI-2025-004",
    date: "04-04-2025",
    status: "Approve",
    priority: "Medium",
    checked: true,
  },
];
export const faultBatchData2: FaultBatch[] = [
  {
    id: "SI-2025-001",
    date: "01-01-2025",
    status: "Pending",
    priority: "High",
    checked: false,
  },
  {
    id: "SI-2025-002",
    date: "02-02-2025",
    status: "Completed",
    priority: "Low",
    checked: false,
  },
  {
    id: "SI-2025-003",
    date: "03-03-2025",
    status: "In progress",
    priority: "High",
    checked: false,
  },
  {
    id: "SI-2025-004",
    date: "04-04-2025",
    status: "Approve",
    priority: "Medium",
    checked: false,
  },
];
export const processingOrderData: ProcessingOrder[] = [
  {
    orderId: "SI-2025-001",
    orderType: "Returned",
    action: "",
  },
  {
    orderId: "SI-2025-002",
    orderType: "Canceled",
    action: "",
  },
  {
    orderId: "SI-2025-003",
    orderType: "Other",
    action: "",
  },
  {
    orderId: "SI-2025-004",
    orderType: "Canceled",
    action: "",
  },
];
